Repository CS2113-AY1819S1-F09-3/main, pull requests merged in 2018-11, with the labels that each got.

#232 v1.3 - EmailWindow
  README.adoc
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/EmailWindow.png
  docs/images/EmailWindowError.png
  docs/team/aaryamNUS.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/QrUtil.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/Email.java
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
  src/main/java/seedu/address/logic/commands/MailCommand.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/ui/EmailWindow.java
  src/main/java/seedu/address/ui/ImportReportWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EmailWindow.fxml
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.high, type.enhancement, type.story

#240 v1.3.1 - Standardised the User Guide
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/Email.java
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/resources/EmailData/Credentials.txt
  src/main/resources/EmailData/Message.txt
Labels: priority.low

#243 Edited User Guide
  docs/UserGuide.adoc
  docs/images/ImportReportWindow.PNG
Labels: type.task

#266 Modified Payment, Attendance, UG, FilterCommand, FilterCommandParser, FindCommand
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.high

#268 Fixed the issues presented in PE1
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/Email.java
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EmailAllCommandParser.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/HistoryCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/main/java/seedu/address/ui/UiPart.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.medium, type.task

#269 Fixed issues in PE1
  docs/UserGuide.adoc
  docs/team/wm28.adoc
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/converters/fileformats/csv/CsvFileTest.java
Labels: priority.high, severity.High

#271 Fix Qr exception issue
  src/main/java/seedu/address/commons/util/QrUtil.java
Labels: type.task

#273 Mid-V1.4 Deliverable: Added remaining tests and updated PPP
  ExportedTestGuestBook.csv
  SE-EDU.md
  SandhyaGopakumar.md
  Sarah.md
  aaryamNUS.md
  docs/team/SarahTaaherBonna.adoc
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high

#277 Refactored some code
  src/main/java/seedu/address/logic/commands/Email.java
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
  src/main/java/seedu/address/logic/commands/EmailSpecificCommand.java
  src/main/java/seedu/address/logic/commands/MailCommand.java
Labels: priority.high, type.enhancement

#278 Improve code quality
  src/main/java/seedu/address/commons/events/ui/ShowImportReportEvent.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/converters/fileformats/SupportedFile.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/ImportReportWindow.java
  src/main/java/seedu/address/ui/PersonDisplay.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/testutil/stubs/CsvConverterStub.java
  src/test/java/seedu/address/testutil/stubs/CsvFileStub.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
  src/test/java/seedu/address/testutil/stubs/ModelStubAcceptingPersonAdded.java
  src/test/java/seedu/address/testutil/stubs/ModelStubContainingTypicalPersons.java
  src/test/java/seedu/address/testutil/stubs/PersonConverterStub.java
  src/test/java/seedu/address/testutil/stubs/SupportedFileStub.java
Labels: type.task

#282 Updated test files to get tests to pass.
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/view/BrowserPanel.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.high

#284 PPP Changes
  docs/team/aaryamNUS.adoc
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.task

#286 PPP Edits
  docs/AboutUs.adoc
  docs/team/aaryamNUS.adoc
Labels: type.task

#289 PPP changes
  docs/team/aaryamnus.adoc
Labels: type.task

#295 UID field is finally done. The mark unmark command uses the UID as well. the UI has a new field to show the UID. Will update the command instructions after the merge
  docs/AboutUs.adoc
  docs/team/tantzeguang.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GeneralMarkCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/converters/CsvConverter.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Uid.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDisplay.java
  src/main/resources/view/PersonDisplay.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/data/data/CsvTest/typicalPersonsGuestList.csv
  src/test/data/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/converters/CsvConverterTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/UidTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high, type.enhancement

#294 Added in Find and Filter parts in Appendix G of DG, updated PPP
  docs/DeveloperGuide.adoc
  docs/team/sarahtaaherbonna.adoc
Labels: type.task

#297 Updated documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ExportCommandSequenceDiagram.PNG
  docs/images/ExportSequenceRefFrame.PNG
  docs/images/ImportCommandSequenceDiagram.PNG
  docs/images/ImportExportClassDiagram.PNG
  docs/images/ImportReportWindowSequenceDiagram.png
  docs/images/ImportSequenceRefFrame.PNG
  docs/team/wm28.adoc
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.task

#292 Rename CsvConverter to CsvPersonConverter
  src/main/java/seedu/address/logic/converters/CsvPersonConverter.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/converters/CsvPersonConverterTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/testutil/stubs/CsvPersonConverterStub.java
Labels: type.task

#300 Fix issue with header not showing on PPP
  docs/UserGuide.adoc
Labels: type.task

#301 Added random generation of UID if the user uses u/00000 in the add command. else it will be user defined.
  guestbook.csv
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GeneralMarkCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/converters/CsvPersonConverterTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: priority.high, type.epic

#304 Modified alignment of Name and UID
  docs/diagrams/FindSequenceDiagram.pptx
  docs/images/FindSequenceDiagram.png
  docs/team/sarahtaaherbonna.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/main/resources/view/PersonListPanel.fxml
Labels: type.task

#306 Modified Mark and Unmark Command examples provided
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
Labels: type.task

#307 Removed bugs from mark and unmark command, modified command descriptions to fit the text box in the UI
  docs/team/tantzeguang.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/GeneralMarkCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/person/Uid.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/model/person/UidTest.java
Labels: severity.Medium, type.bug

#309 Bug fixes for add_guest and import commands
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/testutil/stubs/ModelStubAcceptingPersonAdded.java
  test.csv
Labels: severity.Medium, type.bug

#311 Fix Export bug
  docs/UserGuide.adoc
  docs/images/ExportCommandSequenceDiagram.PNG
  docs/images/ImportReportWindow.PNG
  docs/team/wm28.adoc
  src/main/java/seedu/address/commons/events/ui/ShowImportReportEvent.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/converters/CsvPersonConverter.java
  src/main/java/seedu/address/logic/converters/error/ImportError.java
  src/main/java/seedu/address/ui/ImportReportWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDisplay.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/data/CsvTest/typicalPersonsGuestList.csv
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/converters/CsvPersonConverterTest.java
  src/test/java/seedu/address/logic/converters/fileformats/csv/CsvFileTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
  src/test/java/seedu/address/testutil/stubs/ModelStubAcceptingPersonAdded.java
Labels: priority.high, type.bug, type.task

#312 Clean up repo and update documentation
  Collate-TUI.jar
  SE-EDU.md
  SandhyaGopakumar.md
  Sarah.md
  aaryamNUS.md
  docs/team/wm28.adoc
  guestbook.csv
  kronicler.md
  test.csv
  wm28.md
Labels: type.task

#318 Updated PPP
  docs/diagrams/AddGuestSequenceDiagram.pptx
  docs/images/AddCommandSequenceDiagram.png
  docs/team/tantzeguang.adoc
Labels: status.ongoing

#319 Fix formatting issues
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/sandhyagopakumar.adoc
  docs/team/wm28.adoc
Labels: type.task

#320 Added tests
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: type.task

#323 updating PPP
  docs/team/kronicler.adoc
Labels: type.task

#328 Edited documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ImportCommandSequenceDiagram.PNG
  docs/images/ImportExportClassDiagram.PNG
Labels: type.task

#332 Update DG (manual testing) and PPP
  docs/DeveloperGuide.adoc
  docs/team/kronicler.adoc
Labels: type.task

#331 Added appendix
  docs/DeveloperGuide.adoc
  docs/team/wm28.adoc
  errorsample.csv
  sample.csv
Labels: type.task

#334 updated PPP
  docs/team/kronicler.adoc
Labels: type.task

#336 Updated the model diagram to include the attendance, payment and uid parts
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelComponentClassBetterOopDiagram.png
  docs/images/ModelComponentClassDiagram.png
Labels: type.task

#337 make PPP Fit page limit
  docs/DeveloperGuide.adoc
  docs/images/ExportCommandSequenceDiagram.PNG
  docs/images/ImportCommandSequenceDiagram.PNG
  docs/images/ImportExportClassDiagram.PNG
  docs/images/ImportReportWindowSequenceDiagram.png
Labels: type.task

#338 PPP changes
  docs/UserGuide.adoc
Labels: type.task

#340 Fixed links
  docs/team/wm28.adoc
Labels: type.task

#342 Final updates to UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/UiComponentClassDiagram.png
  docs/team/aaryamnus.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EmailAllCommand.java
  src/main/java/seedu/address/logic/commands/EmailSpecificCommand.java
  src/main/java/seedu/address/logic/commands/MailCommand.java
  src/test/java/seedu/address/logic/commands/EmailAllCommandTest.java
  src/test/java/seedu/address/logic/commands/EmailSpecificCommandTest.java
  src/test/java/seedu/address/logic/commands/MailCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.high

#343 Minor edits
  docs/DeveloperGuide.adoc
Labels: type.task

#345 final check
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/aaryamnus.adoc
Labels: priority.high

#349 User Guide edit
  docs/UserGuide.adoc
Labels: priority.high
