Repository CS2113-AY1819S1-F09-3/main, pull requests merged in 2018-10, with the labels that each got.

#71 Initial Mark command created
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
Labels: priority.high, type.enhancement, type.story, type.task

#75 v1.1 deliverable
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
Labels: priority.high, type.story, type.task

#74 Initial import command created
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CsvParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
Labels: priority.high, type.enhancement, type.story

#83 Updated some classes, User guide and Developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
Labels: priority.high

#88 Ui layout changes
  src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionClearedEvent.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDisplay.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDisplay.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.medium, type.enhancement, type.task

#100 Added titles Ui components
  src/main/resources/view/PersonDisplay.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: priority.medium, type.enhancement, type.task

#113 Created command to add event details and updated all tests
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.high, type.story

#112 Mid-V1.2 Deliverable: Created Payment Attribute. Modified all files, including tests, to reflect new attribute. Ensured only gmail can be used as email, specifically gmail.com.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CsvParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDisplay.java
  src/main/resources/view/PersonDisplay.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/data/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high

#131 Refactored code for MarkCommand
  src/main/java/seedu/address/logic/commands/MarkCommand.java
Labels: priority.high, type.task

#135 Mid V1.2 Deliverable - addTag() command, removeTag() command, relevant tests and refactoring of tag colour generation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDisplay.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high, type.story, type.task

#138 Fixed some test case issues, added tests for addtag() and removeTag()
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/PersonDisplay.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, type.task

#139 Made edits to the User Guide to fit the language for CS2101
  docs/UserGuide.adoc
Labels: severity.Low, type.task

#143 Fixed author issues in sourcetree
  docs/DeveloperGuide.adoc
Labels: priority.low

#146 PersonDisplay Ui changes
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDisplay.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: severity.Low, type.bug

#152 Bug fix: PersonDisplay alignment
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDisplay.fxml
Labels: severity.Medium, type.bug

#153 Added in Filter details in DeveloperGuide.adoc and attempted to handle prefix in FilterCommand.
  docs/DeveloperGuide.adoc
  docs/diagrams/FilterSequenceDiagram.pptx
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
Labels: priority.high, severity.Medium

#155 Attempt to get FilterSequenceDiagram.png to be seen on website DevGuide.
  docs/diagrams/FilterSequenceDiagram.pptx
  docs/images/FilterSequenceDiagram.png
Labels: priority.medium

#156 Import command refractor
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/converters/CsvConverter.java
  src/main/java/seedu/address/logic/converters/PersonConverter.java
  src/main/java/seedu/address/logic/converters/exceptions/PersonDecodingException.java
  src/main/java/seedu/address/logic/converters/exceptions/PersonEncodingException.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: priority.high, type.task

#157 Export command added
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/converters/CsvConverter.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
Labels: priority.high, type.enhancement

#162 Created DeleteEvent Command
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.task

#170 v1.2 - Added sequence diagrams and usage functionality of removeTag() and addTag() commands
  docs/DeveloperGuide.adoc
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/images/AddTagRemoveTagSequenceDiagram.png
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
Labels: priority.high, type.task

#173 CsvUtil class refractor
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/converters/CsvConverter.java
  src/main/java/seedu/address/logic/converters/PersonConverter.java
  src/main/java/seedu/address/logic/converters/fileformats/AdaptedPerson.java
  src/main/java/seedu/address/logic/converters/fileformats/SupportedFile.java
  src/main/java/seedu/address/logic/converters/fileformats/SupportedFileFormat.java
  src/main/java/seedu/address/logic/converters/fileformats/csv/CsvAdaptedPerson.java
  src/main/java/seedu/address/logic/converters/fileformats/csv/CsvFile.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: priority.high, status.ongoing, type.task

#176 Added Import/Export command in Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/ExportCommandSequenceDiagram.PNG
  docs/images/ExportSequenceRefFrame.PNG
  docs/images/ImportCommandSequenceDiagram.PNG
  docs/images/ImportExportClassDiagram.PNG
  docs/images/ImportSequenceRefFrame.PNG
Labels: type.task

#189 v1.2 - Added Mail Tag Command that sends emails to guests via an INDEX parameter
  build.gradle
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/MailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MailCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
Labels: priority.high, type.enhancement, type.story

#192 Removed restriction on type of email to use in Email.java
  src/main/java/seedu/address/model/person/Email.java
Labels: priority.high, type.task

#202 Initial Id field code added.
  src/main/java/seedu/address/model/person/Uid.java
Labels: priority.high, status.ongoing, type.task

#203 Added Tests for CsvConverter and CsvFile
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/converters/fileformats/csv/CsvAdaptedPerson.java
  src/main/java/seedu/address/logic/converters/fileformats/csv/CsvFile.java
  src/test/data/data/CsvTest/typicalPersonsGuestList.csv
  src/test/java/seedu/address/logic/converters/CsvConverterTest.java
  src/test/java/seedu/address/logic/converters/fileformats/csv/CsvFileTest.java
Labels: priority.high

#217 Import report window
  src/main/java/seedu/address/commons/events/ui/ShowImportReportEvent.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/error/ImportError.java
  src/main/java/seedu/address/ui/ImportReportWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ImportReportWindow.fxml
Labels: priority.high, type.enhancement

#224 Project Portfolio
  README.adoc
  docs/UserGuide.adoc
  docs/team/wm28.adoc
Labels: type.task
